services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
    env_file:
      - .env
      - paths.env
    stop_grace_period: 120s

  beacond:
    image: ubuntu:24.04
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
      - ./entrypoints/:/entrypoints/
    env_file:
      - .env
      - paths.env
    ports:
      - "${PORT__BEACOND_NODE_API:-3500}:3500"
      - "${PORT__BEACOND_GRPC:-9090}:9090"
      - "${PORT__BEACOND_PROMETHEUS:-26660}:26660"
      - "${PORT__BEACOND_API:-1317}:1317/tcp"
      - "${PORT__BEACOND_P2P:-26656}:26656/tcp"
      - "${PORT__BEACOND_COMETBFT_RPC:-26657}:26657/tcp"
      - "${PORT__BEACOND_ABCI_APP:-26658}:26658/tcp"
    entrypoint: /entrypoints/beacond.sh
    depends_on:
      build:
        condition: service_completed_successfully

  reth:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        RUN apt-get update && apt-get install -y curl
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
      - ./entrypoints/:/entrypoints/
    env_file:
      - .env
      - paths.env
    ports:
      - "${PORT__RETH_RPC:-8545}:8545"
      - "${PORT__RETH_METRICS:-6060}:6060"
      - "${PORT__RETH_PEERING_UDP:-30303}:30303/udp"
      - "${PORT__RETH_PEERING_TCP:-30303}:30303/tcp"
    entrypoint: /entrypoints/reth.sh
    depends_on:
      build:
        condition: service_completed_successfully
