services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
    env_file:
      - .env
      - paths.env

  beacond:
    image: ubuntu:24.04
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
      - ./entrypoints/:/entrypoints/
    env_file:
      - .env
      - paths.env
    ports:
      - "3500:3500" # node api
      - "9091:9090" # grpc
      - "26660:26660" # prometheus
      - "1317:1317/tcp" # api
      - "26650:26656/tcp" # p2p
      - "26640:26657/tcp" # cometbft rpc
      - "26658:26658/tcp" # abci app
    entrypoint: /entrypoints/beacond.sh
    depends_on:
      build:
        condition: service_completed_successfully

  reth:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:24.04
        RUN apt-get update && apt-get install -y curl
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - ./data/beacon-kit:/app/data/beacon-kit
      - ./data/bin:/app/data/bin
      - ./data/beacond:/app/data/beacond
      - ./data/reth:/app/data/reth
      - ./data/snapshots:/app/data/snapshots
      - ./entrypoints/:/entrypoints/
    env_file:
      - .env
      - paths.env
    ports:
      - "8545:8545" # rpc
      - "7300:6060" # metrics
      - "30303:30303/udp" # peering
      - "30303:30303/tcp" # peering
    entrypoint: /entrypoints/reth.sh
    depends_on:
      build:
        condition: service_completed_successfully
